import assert from "node:assert/strict";
import { calculateOfferArea, getAreaCalculatorTotalSqm } from "../../lib/offer/workspace-area";

const calculation = calculateOfferArea({
  groundFloorSqm: 110,
  firstFloorSqm: 90,
  alfrescoSqm: 8,
  porchSqm: 3,
  garageSqm: 20,
  grannyFlatSqm: 0,
  slabRatePerSqm: 220,
  dropEdgeLinealMeters: 10,
  dropEdgeRate: 280,
  frameGroundRatePerSqm: 125,
  frameFirstRatePerSqm: 135,
  steelAllowance: 10000,
  frameInstallAllowance: 15000,
  extraTruckCost: 0,
  brickGroundLinealMeters: 76,
  brickFirstLinealMeters: 36,
  brickGroundHeight: 3,
  brickFirstHeight: 3.3,
  bricksPerSqm: 50,
  sandRatePerThousandBricks: 100,
  cementRatePerHundredBricks: 15,
  tileAreaSqm: 212.3,
  tileSupplyRatePerSqm: 30,
  tilerRatePerSqm: 70,
  tileAnglesAllowance: 0,
});

assert.deepEqual(calculation, {
  slabAreaSqm: 141,
  slabCost: 31020,
  dropEdgeBeamCost: 2800,
  slabPackageTotal: 33820,
  frameGroundFloorCost: 17625,
  frameFirstFloorCost: 12150,
  framePackageTotal: 54775,
  brickGroundSqm: 228,
  brickFirstSqm: 118.8,
  brickCount: 17340,
  brickSandCost: 1734,
  brickCementCost: 2601,
  tileSupplyCost: 6369,
  tilerCost: 14861,
  tilePackageTotal: 21230,
});

assert.equal(
  getAreaCalculatorTotalSqm({
    groundFloorSqm: 110,
    firstFloorSqm: 90,
    alfrescoSqm: 8,
    porchSqm: 3,
    garageSqm: 20,
    grannyFlatSqm: 0,
    slabRatePerSqm: 220,
    dropEdgeLinealMeters: 10,
    dropEdgeRate: 280,
    frameGroundRatePerSqm: 125,
    frameFirstRatePerSqm: 135,
    steelAllowance: 10000,
    frameInstallAllowance: 15000,
    extraTruckCost: 0,
    brickGroundLinealMeters: 76,
    brickFirstLinealMeters: 36,
    brickGroundHeight: 3,
    brickFirstHeight: 3.3,
    bricksPerSqm: 50,
    sandRatePerThousandBricks: 100,
    cementRatePerHundredBricks: 15,
    tileAreaSqm: 212.3,
    tileSupplyRatePerSqm: 30,
    tilerRatePerSqm: 70,
    tileAnglesAllowance: 0,
  }),
  231,
);
