import { Lead } from './types';

export const dummyLeads: Lead[] = [
  {
    id: 1,
    name: 'Ravinder Singh',
    phone: '0432 156 789',
    email: 'ravinder@email.com',
    location: 'Penrith, NSW',
    source: 'Google Ads',
    sourceDetail: 'builder near me',
    stage: 'New',
    assigned: null,
    budget: 'Not Discussed',
    type: 'Not Specified',
    notes: 'First enquiry via Google Ads. Interested in 4BR home.',
    followupDate: null,
    followupTime: null,
    followupNotes: '',
    history: [
      {
        date: '2025-07-05',
        time: '09:15',
        action: 'Lead captured',
        detail: 'Auto-captured from Google Ads — keyword: builder near me',
        type: 'system',
      },
    ],
    created: '2025-07-05',
    urgent: false,
  },
  {
    id: 2,
    name: 'Priya Sharma',
    phone: '0445 678 901',
    email: 'priya.s@email.com',
    location: 'Auburn, NSW',
    source: 'Google Ads',
    sourceDetail: 'home builder NSW',
    stage: 'New',
    assigned: 'Guri Singh',
    budget: '$350K - $500K',
    type: 'New Home',
    notes: 'Wants open-plan living with optional theatre room. Land already owned.',
    followupDate: '2025-07-07',
    followupTime: '15:30',
    followupNotes: 'Send revised floor plan options email',
    history: [
      {
        date: '2025-07-05',
        time: '11:30',
        action: 'Lead captured',
        detail: 'Auto-captured from Google Ads — keyword: home builder NSW',
        type: 'system',
      },
    ],
    created: '2025-07-05',
    urgent: true,
  },
  {
    id: 3,
    name: 'James Wilson',
    phone: '0421 345 678',
    email: 'james.w@email.com',
    location: 'Hornsby, NSW',
    source: 'Google Ads',
    sourceDetail: 'custom home builder',
    stage: 'New',
    assigned: 'Guri Singh',
    budget: '$500K - $700K',
    type: 'New Home',
    notes: 'Land purchased at Hornsby Heights. Wants 4BR modern home.',
    followupDate: '2025-07-07',
    followupTime: '17:00',
    followupNotes: 'Initial consultation call',
    history: [
      {
        date: '2025-07-06',
        time: '08:45',
        action: 'Lead captured',
        detail: 'Auto-captured from Google Ads — keyword: custom home builder',
        type: 'system',
      },
    ],
    created: '2025-07-06',
    urgent: false,
  },
  {
    id: 4,
    name: 'Simran Gill',
    phone: '0456 789 012',
    email: 'simran.g@email.com',
    location: 'Ryde, NSW',
    source: 'Referral',
    sourceDetail: 'Harpreet Kaur',
    stage: 'New',
    assigned: 'Guri Singh',
    budget: 'Not Discussed',
    type: 'Not Specified',
    notes: 'Referred by Harpreet Kaur (Penrith project). Trusted lead.',
    followupDate: '2025-07-08',
    followupTime: '11:00',
    followupNotes: '',
    history: [
      {
        date: '2025-07-06',
        time: '14:00',
        action: 'Lead captured',
        detail: 'Referral from Harpreet Kaur — Penrith Residence client',
        type: 'referral',
      },
    ],
    created: '2025-07-06',
    urgent: false,
  },
  {
    id: 5,
    name: 'Manpreet Dhillon',
    phone: '0478 901 234',
    email: 'manpreet.d@email.com',
    location: 'Liverpool, NSW',
    source: 'Google Ads',
    sourceDetail: 'duplex builder Sydney',
    stage: 'Contacted',
    assigned: 'Amrit Singh',
    budget: '$350K - $500K',
    type: 'Duplex',
    notes: 'Interested in duplex construction. Has two adjacent blocks.',
    followupDate: '2025-07-08',
    followupTime: '10:00',
    followupNotes: 'Site visit scheduled',
    history: [
      {
        date: '2025-07-02',
        time: '09:00',
        action: 'Lead captured',
        detail: 'Auto-captured from Google Ads',
        type: 'system',
      },
      {
        date: '2025-07-03',
        time: '10:30',
        action: 'Called',
        detail: 'Discussed duplex options. Client interested in modern design.',
        type: 'call',
      },
      {
        date: '2025-07-04',
        time: '09:00',
        action: 'Email sent',
        detail: 'Sent duplex portfolio PDF with 5 designs',
        type: 'email',
      },
    ],
    created: '2025-07-02',
    urgent: false,
  },
  {
    id: 6,
    name: 'Harpreet Kaur',
    phone: '0467 234 567',
    email: 'harpreet.k@email.com',
    location: 'Penrith, NSW',
    source: 'Repeat Client',
    sourceDetail: 'Previous client',
    stage: 'Qualified',
    assigned: 'Deepak Sharma',
    budget: '$700K+',
    type: 'Renovation',
    notes: 'Past client. Now interested in home renovation. Highly qualified.',
    followupDate: '2025-07-09',
    followupTime: '14:00',
    followupNotes: 'Schedule site survey',
    history: [
      {
        date: '2024-05-15',
        time: '10:00',
        action: 'Previous project',
        detail: 'Completed Penrith Residence — 4BR home',
        type: 'system',
      },
      {
        date: '2025-07-01',
        time: '11:00',
        action: 'Called',
        detail: 'Called regarding renovation interest',
        type: 'call',
      },
      {
        date: '2025-07-04',
        time: '16:00',
        action: 'Qualified',
        detail: 'Sent detailed renovation proposal',
        type: 'email',
      },
    ],
    created: '2025-07-01',
    urgent: false,
  },
  {
    id: 7,
    name: 'Rajesh Kumar',
    phone: '0489 567 890',
    email: 'rajesh.k@email.com',
    location: 'Campbelltown, NSW',
    source: 'Facebook Ads',
    sourceDetail: 'Home builder ads',
    stage: 'Quoted',
    assigned: 'Guri Singh',
    budget: '$200K - $350K',
    type: 'Granny Flat',
    notes: 'Quoted $320K for granny flat. Awaiting decision.',
    followupDate: '2025-07-12',
    followupTime: '10:00',
    followupNotes: 'Follow up on quote',
    history: [
      {
        date: '2025-06-20',
        time: '08:00',
        action: 'Lead captured',
        detail: 'From Facebook Ads campaign',
        type: 'system',
      },
      {
        date: '2025-06-25',
        time: '11:00',
        action: 'Called',
        detail: 'Initial consultation',
        type: 'call',
      },
      {
        date: '2025-06-28',
        time: '14:00',
        action: 'Quote sent',
        detail: 'Sent formal quote — $320K',
        type: 'email',
      },
    ],
    created: '2025-06-20',
    urgent: false,
  },
  {
    id: 8,
    name: 'Anita Patel',
    phone: '0451 234 567',
    email: 'anita.p@email.com',
    location: 'Strathfield, NSW',
    source: 'Website',
    sourceDetail: 'Contact form',
    stage: 'Negotiating',
    assigned: 'Amrit Singh',
    budget: '$500K - $700K',
    type: 'Townhouse',
    notes: 'Townhouse project. Currently negotiating final terms.',
    followupDate: '2025-07-10',
    followupTime: '15:00',
    followupNotes: 'Contract discussion scheduled',
    history: [
      {
        date: '2025-06-15',
        time: '10:00',
        action: 'Lead captured',
        detail: 'Contact form submission from website',
        type: 'system',
      },
      {
        date: '2025-06-18',
        time: '11:00',
        action: 'Called',
        detail: 'Detailed project discussion',
        type: 'call',
      },
      {
        date: '2025-06-22',
        time: '14:00',
        action: 'Quote sent',
        detail: 'Sent detailed proposal',
        type: 'email',
      },
      {
        date: '2025-07-02',
        time: '10:30',
        action: 'Negotiating',
        detail: 'In discussions regarding payment terms',
        type: 'call',
      },
    ],
    created: '2025-06-15',
    urgent: false,
  },
  {
    id: 9,
    name: 'Michael Chen',
    phone: '0473 456 789',
    email: 'michael.c@email.com',
    location: 'Chatswood, NSW',
    source: 'Referral',
    sourceDetail: 'Rajesh Kumar',
    stage: 'Won',
    assigned: 'Deepak Sharma',
    budget: '$350K - $500K',
    type: 'New Home',
    notes: 'Project won! Construction starting July 15.',
    followupDate: '2025-07-15',
    followupTime: '09:00',
    followupNotes: 'Project kickoff meeting',
    history: [
      {
        date: '2025-06-10',
        time: '09:00',
        action: 'Lead captured',
        detail: 'Referral from Rajesh Kumar',
        type: 'referral',
      },
      {
        date: '2025-06-12',
        time: '10:30',
        action: 'Called',
        detail: 'Initial consultation',
        type: 'call',
      },
      {
        date: '2025-06-18',
        time: '14:00',
        action: 'Quote sent',
        detail: 'Proposal sent',
        type: 'email',
      },
      {
        date: '2025-06-28',
        time: '11:00',
        action: 'Contract signed',
        detail: 'Contract signed. Project won!',
        type: 'system',
      },
    ],
    created: '2025-06-10',
    urgent: false,
  },
  {
    id: 10,
    name: 'Lisa Thompson',
    phone: '0465 789 012',
    email: 'lisa.t@email.com',
    location: 'Westmead, NSW',
    source: 'Google Ads',
    sourceDetail: 'affordable home builder',
    stage: 'Lost',
    assigned: 'Guri Singh',
    budget: '$200K - $350K',
    type: 'Renovation',
    notes: 'Lost to competitor. Budget constraints.',
    followupDate: '2025-07-15',
    followupTime: '10:00',
    followupNotes: 'Follow up in 3 months',
    history: [
      {
        date: '2025-05-20',
        time: '09:00',
        action: 'Lead captured',
        detail: 'From Google Ads',
        type: 'system',
      },
      {
        date: '2025-05-22',
        time: '10:00',
        action: 'Called',
        detail: 'Initial consultation',
        type: 'call',
      },
      {
        date: '2025-05-28',
        time: '14:00',
        action: 'Quote sent',
        detail: 'Sent quote',
        type: 'email',
      },
      {
        date: '2025-06-05',
        time: '11:00',
        action: 'Lost',
        detail: 'Client chose competitor due to budget constraints',
        type: 'system',
      },
    ],
    created: '2025-05-20',
    urgent: false,
  },
];
